---
- name: Configuring PAMM's environment for TTY
  hosts: pamm
  sudo: yes
  remote_user: root

  tasks:
    - include: baseline.yml
    - include: install_node.yml
    - include: install_rpm.yml
      vars:
        rpm_app_name: "Java JDK 8u51-x64"
        rpm_filename : jdk-8u51-linux-x64.rpm
    - include: install_mongo.yml
      vars:
        repo: mongo-db.repo
    - include: install_mariadb.yml
      vars:
        db_user: admin
        db_pwd: Passw0rd!
        repo: mariadb_10.repo

